### ISSUE TITLE
BME280 and error

### ISSUE THREAD

**Issue by pacioc193** [999LV/SmartVirtualThermostat#12]
Hey man,

Thanks for your works! Very beautiful to see your working system!!

I need help, the plugin cannot find the temperatura sensor but Domoticz can read it very well. Some times the thermostat read the temperature, but 80% are failure! Can you help me?

This is the JSON that Domoticz give me back on JSON

192.168.1.41:8080/json.htm?type=devices&rid=1

{
   "ActTime" : 1535575388,
   "AstrTwilightEnd" : "21:58",
   "AstrTwilightStart" : "04:53",
   "CivTwilightEnd" : "20:40",
   "CivTwilightStart" : "06:11",
   "DayLength" : "13:27",
   "NautTwilightEnd" : "21:17",
   "NautTwilightStart" : "05:33",
   "ServerTime" : "2018-08-29 22:43:08",
   "SunAtSouth" : "13:05",
   "Sunrise" : "06:42",
   "Sunset" : "20:09",
   "app_version" : "4.9700",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 978.5,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "26.1 C, 52 %, 978.5 hPa",
         "Description" : "",
         "DewPoint" : "15.48",
         "Favorite" : 1,
         "Forecast" : 4,
         "ForecastStr" : "Cloudy",
         "HardwareID" : 2,
         "HardwareName" : "Temperatura",
         "HardwareType" : "I2C sensor BME280 Temp+Hum+Baro",
         "HardwareTypeVal" : 96,
         "HaveTimeout" : false,
         "Humidity" : 52,
         "HumidityStatus" : "Comfortable",
         "ID" : "0001",
         "LastUpdate" : "2018-08-29 22:42:44",
         "Name" : "Temperatura",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Weather Station",
         "Temp" : 26.100000000000001,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by pacioc193** [comment]
This is tha webpage that script check

{
   "ActTime" : 1535576165,
   "AstrTwilightEnd" : "21:58",
   "AstrTwilightStart" : "04:53",
   "CivTwilightEnd" : "20:40",
   "CivTwilightStart" : "06:11",
   "DayLength" : "13:27",
   "NautTwilightEnd" : "21:17",
   "NautTwilightStart" : "05:33",
   "ServerTime" : "2018-08-29 22:56:05",
   "SunAtSouth" : "13:05",
   "Sunrise" : "06:42",
   "Sunset" : "20:09",
   "app_version" : "4.9700",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "Barometer" : 978.60000000000002,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "25.7 C, 52 %, 978.6 hPa",
         "Description" : "",
         "DewPoint" : "15.11",
         "Favorite" : 1,
         "Forecast" : 4,
         "ForecastStr" : "Cloudy",
         "HardwareID" : 2,
         "HardwareName" : "Temperatura",
         "HardwareType" : "I2C sensor BME280 Temp+Hum+Baro",
         "HardwareTypeVal" : 96,
         "HaveTimeout" : false,
         "Humidity" : 52,
         "HumidityStatus" : "Comfortable",
         "ID" : "0001",
         "LastUpdate" : "2018-08-29 22:55:45",
         "Name" : "Temperatura",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Weather Station",
         "Temp" : 25.699999999999999,
         "Timers" : "false",
         "Type" : "Temp + Humidity + Baro",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "26.1 C",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "Termostato",
         "HardwareType" : "Smart Virtual Thermostat",
         "HardwareTypeVal" : 94,
         "HaveTimeout" : false,
         "ID" : "00040006",
         "LastUpdate" : "2018-08-29 22:32:49",
         "Name" : "Temperatura Casa",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 26.100000000000001,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 6,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "8"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by 999LV** [comment]
This is unrelated to the plugin... the domoticz device for your sensor is a combo device holding multiple values (temp, hum, baro), not a domoticz temperature sensor... different devices.

So either a separate domoticz temperature device already has been created when installing your sensor (it may be in hidden status) or you have to create yourself (see 
https://www.domoticz.com/forum/viewtopic.php?t=19418&start=20#p153248)

Generally speaking these questions/issues are best posted on the domoticz forum than on GitHub as not related to development. Thanks

**Comment by pacioc193** [comment]
I've the same error after creating a dummy element.... I write it on the forum. Is not possible to poll data also on mutiple values... The json return always temperature in a single value!
