### ISSUE TITLE
Segmentation fault after few seconds.

### ISSUE THREAD

**Issue by twpeltenburg** [999LV/SmartVirtualThermostat#16]
I get the following error when trying to use SVT.
Domoticz version: V4.10215
Python version: 3.4.2
OS: Raspberry Pi

2018-11-21 23:56:36.176 Error: Domoticz(pid:6271, tid:6277('PluginMgr')) received fatal signal 11 (Segmentation fault)
2018-11-21 23:56:36.176 Error: siginfo address=0xa8293f40, address=0x7205a8

**Comment by 999LV** [comment]
Your log suggests it is the plugin manager that crashes if I read correctly... is the SVT plugin installed at all ?

PS: issues like this should be posted on the domoticz forum... github is for developpers

**Comment by twpeltenburg** [comment]
Yes the plugin is installed. When I enable the hardware Domoticz crashes and above statements are shown in the log.

**Comment by 999LV** [comment]
I suspect this is due to your libssl setup that causes a python crash when the urllib.request module is loaded by the plugin. I recommend you do a search on the domoticz forum on this... plenty of threads about it.
This is not a plugin code issue but rather related to your host system
