### ISSUE TITLE
Error callling 'http://...

### ISSUE THREAD

**Issue by Kiritzai** [999LV/SmartVirtualThermostat#2]
Seems i've found a bug or unwriting feature.
Recently added **Website Protection** and suddenly my Thermostat couldn't launch on Auto, switch right back to Off state.

The Following error occured.
```
Dec 26 13:50:02 domotica domoticz[1273]: 2017-12-26 13:50:02.322  Error: (Thermostat) Error calling 'http://192.168.1.20:8080/json.htm?type=devices&filter=temp&used=true&order=Name'
Dec 26 13:50:02 domotica domoticz[1273]: 2017-12-26 13:50:02.322  Error: (Thermostat) No Inside Temperature found... Switching Thermostat Off
Dec 26 13:50:02 domotica domoticz[1273]: 2017-12-26 13:50:02.323  Error: (Thermostat) Error calling 'http://192.168.1.20:8080/json.htm?type=command&param=switchlight&idx=2&switchcmd=Off'
```

Tried reaching the following address:
`http://192.168.1.20:8080/json.htm?type=command&param=switchlight&idx=2&switchcmd=Off`

Unforunately it said that Domoticz was offline, well this wasn't the case.
Turned of my **Website Protection** and suddenly I could access the web address and also the Thermostat worked.

Seems the SVT ( Auto Thermostat ) doesn't work with **Website Protection**.
Truly hope you can find a solution to this issue.

**Comment by 999LV** [comment]
I do not know what you mean by « website protection », but the manual for the plugin is very clear:
QUOTE
password free http access to domoticz must be granted to the IP of the system (e.g. usually 127.0.0.1 when the plugin runs on the same system as the domoticz install to be driven by the virtual thermostat)
UNQUOTE
You can (and probably should...) enable password protection for domoticz, and whitelist in domoticz settings the local IP or even better the localhost loopback interface. I close this case.
