### ISSUE TITLE
temperature configuration in homekit change only by whole degree

### ISSUE THREAD

**Issue by skywalker1979** [999LV/SmartVirtualThermostat#21]
on homekit on the iphone, it's only possible to change from whole degree to whole degree.
i'm not sure that it's the thermostat causing this, but other devices are ok.
So, on the screen i see only like "20°" and if i slide the next value is "21°". There is no 20.1 and neither 20.5.".

Also, when you leave the screen of temperature configuration, the value that shows is still the previous one. (i guess that has to do with the fact that the temperature has not been pushed to MQTT?)

**Comment by 999LV** [comment]
@skywalker1979 , I doubt this is related to the plugin (temperature with decimals can be set when using the GUI or when sending set point value via the domoticz Json API). Suggest indeed that you investigate MQTT gateway.

**Comment by skywalker1979** [comment]
sorry for the late reply.....i see....i'll check if there is anything that can be changed....! thanks....impressive work on this piece of software!
