### ISSUE TITLE
Make a version of this plugin for the Mozilla WebThings Gateway

### ISSUE THREAD

**Issue by flatsiedatsie** [999LV/SmartVirtualThermostat#25]
Like many people, I have switched from Domoticz to the Mozilla WebThings Gateway. But I really miss this plugin.

I'm thinking: would it be possible to create a version for the WebThings Gateway?

**Comment by flatsiedatsie** [comment]
Phrased differently: how difficult do you think it will be for someone to take the core of your plugin and re-work it for another platform?

**Comment by 999LV** [comment]
Interesting question... it took me a fair amount of work to port the original plugin written in Lua for Vera platform to Python for domoticz, but I am not a professional coder. You need to find a competent developper who also is motivated to maintain it.

**Comment by flatsiedatsie** [comment]
I had a closer look at the code to find the PID aspects, the "engine" as it were, but I'm not sure I found it?
