### ISSUE TITLE
About 0.4.8 heating off

### ISSUE THREAD

**Issue by boscorelly** [999LV/SmartVirtualThermostat#30]
0.4.8: change behavior if no valid inside temperature reading: switch heating off instead of switching the thermostat off... then if and when there is a valid temperature the thermostat resumes work

It is not the case. 
Often, my sensor is not reachable when he is calculating temp. 
Here is the exemple :

2020-03-30 18:23:46.140 Error: (Thermo) skipping timed out temperature sensor 'Température Chambre'
2020-03-30 18:23:46.143 Error: (Thermo) No Inside Temperature found... Switching Thermostat Off

Then, until now at 4am no heating. 
Please remove this or add an option to chose what to do.

**Comment by 999LV** [comment]
Bonjour,

C'est une sécurité pour protéger contre une surchauffe. Je ne pense pas opportun de la désactiver car le plugin ne peut pas savoir si une sonde est HS ou simplement rencontre une erreur temporaire de communication.
Pour ton besoin, et en connaissance de cause, tu peux désactiver cette securité en commentant les lignes 500 et 501 du code de plugin.py:
   

>#Domoticz.Error("No Inside Temperature found: Switching heating Off")

>#self.switchHeat(False)

**Comment by boscorelly** [comment]
Je comprends. Mais alors il y a un problème parce qu’il s’arrête tout simplement de fonctionner, alors qu’il devrait réessayer de relancer le chauffage...

**Comment by 999LV** [comment]
C’est prévu lignes 490 à 494... testé sans problèmes

**Comment by boscorelly** [comment]
chez moi ça ne fonctionne pas :/
Tu pourrais augmenter la verbosité de ses actions ? Parce qu'une fois 
qu'il s'est mit off, il ne fait strictement plus rien...
