### ISSUE TITLE
[Suggestion] Global setpoint

### ISSUE THREAD

**Issue by boscorelly** [999LV/SmartVirtualThermostat#32]
When you have multiples thermostat, you have several setpoints. I suggest to have a setpoint "global" and an option "global/override" in each setpoint to be able to use the global setpoint or the local setpoint.

**Comment by 999LV** [comment]
The plugin already creates many devices and in domoticz the number plugin parameters is fixed to 6 maximum (hence the cvs values in existing parameters)... and adding even more devices or parameters will only add complexity for most users and breaking changes may need to be introduced from earlier versions.
I think you can achieve what you suggest with lua, python or dzvents scripts that will set individual setpoints to your need, based on some virtual switches and a virtual global setpoint of your liking ?
