### ISSUE TITLE
Set point value NAN - can't change

### ISSUE THREAD

**Issue by szabot79** [999LV/SmartVirtualThermostat#33]
Hi! Today I get an issue: On my phone I tried to change setpoint normal and got NAN value. Unfortunatley I pushed SET button and now value is NAN and I can't change this device. Even in utility even from PC browser. Only rename. Any suggestion? What I have to check?

**Comment by boscorelly** [comment]
duplicate the item (do on devices, clic thermostat, annd add the bottom of the page, add) then delete the old one.
maybe a bug with user variables

**Comment by szabot79** [comment]
Hi!

I attached my relevant user variables. Can you have a look on it please?

Camille Ollié <notifications@github.com> ezt írta (időpont: 2020. ápr. 7.,
K, 11:23):

**Comment by szabot79** [comment]
Forget it! I updated with HTTP JSON command and now working well! :)

Tamás Szabó <szabot79@gmail.com> ezt írta (időpont: 2020. ápr. 7., K,
15:41):

**Comment by 999LV** [comment]
Was about to suggest that solution. Glad it worked for you. Closing the issue thread then.
