### ISSUE TITLE
High/Low costs

### ISSUE THREAD

**Issue by vzmuda** [999LV/SmartVirtualThermostat#36]
Hello,
thank you very much for a lot of your work. Everythong works perfect,but I am missing one function. Is it possible to set here idx of device,which signalize high or low costs of electricity?
Thank ou for your answer

**Comment by 999LV** [comment]
Hi. Thanks for your appreciation.
However, I do not understand your point. This being GitHub (not a domoticz user forum) I assume you can submit code doing what you request ?
