### ISSUE TITLE
Sensor check

### ISSUE THREAD

**Issue by Jacobsentertainment** [999LV/SmartVirtualThermostat#37]
Hi 

I had a couple of times now an issue with the svt that it keeps heating due to an fault in the temperature sensors.
Once I lost the temperature input and this resulted in all value's to 0° And a couple of times I had the temperature sensors to freeze up.  
Is it possible to add an check in the svt that if an temperature sensor is lost or returns a static temperature for an set time that the system turns it self in pause mode ?

**Comment by 999LV** [comment]
Hi,

there already is a time-out check for temp sensors: if a sensor is timed out for domoticz (based on the domoticz settings), then it is ignored by the plugin. And if all inside temp sensors are timed out, then the plugin switches the heating off for safety (see line 500+ in plugin.py).

not sure what more you have in mind...

**Comment by Jacobsentertainment** [comment]
Hi,

The issue is that there was an temperature displayed in domoticz, but due to some external reason this wasn't updated (frozen up) In this case svt keeps the heating switch on till it sees an temperature increase to its set point.
Even domoticz sees it as an normal temperature input although it had stopped updating for 6 hours. 
So in addition to having an failing or missing temperature input svt could also check the last time there was an readout of the sensor, normally this is updated every 5minutes, if this would be "say" 30 minutes then go to pause till there is an new recent update. 

Regards Olaf

**Comment by 999LV** [comment]
At the risk of being a bit blunt... please check your domoticz settings for sensors timeout... mine is set at 60 mins... if a sensor is not updated in that time period, then it is considered by domoticz as timedout (red marking in GUI) and likewise excluded by the plugin. If all sensors (assuming there are several) are timed out, then the plugin will switch off.
Period and not change on this behavior under my watch.
