### ISSUE TITLE
SVT and stove thermostat

### ISSUE THREAD

**Issue by piotrux** [999LV/SmartVirtualThermostat#38]
Hello I have a question. I have a regulator in which I can control the temperature, not on / off. That means, my thermostat controls the stove, I would like a virtual thermostat to control this thermostat depending on the temperature read from netatmo, internal and external temperature. there is a possibility? I can't turn the stove on and off.
Domoticz script to control thermostat on stove:

commandArray = {}
for deviceName,deviceValue in pairs(devicechanged) do
    print ("Device based event fired on '"..deviceName.."', value '"..tostring(deviceValue).."'");
if (deviceName=='Zadana temperatura miarkownika') then

commandArray['OpenURL'] = "http://192.168.0.11/control?cmd=event,setTemp="..tostring(deviceValue);
   end
   end

return commandArray

**Comment by 999LV** [comment]
Please do not reopen this issue thread. Your suggestion is a no go... the best explanation is a recent post on the domoticz forum: https://www.domoticz.com/forum/viewtopic.php?p=264754#p264754

in short, the SVT plugin replaces existing thermostats... no more, no less.

that being said, the code is free based on MIT licence terms for you to adapt to whatever you want. Happy new year
