### ISSUE TITLE
Give more insight on the internals of the thermostat

### ISSUE THREAD

**Issue by rrozema** [999LV/SmartVirtualThermostat#48]
I wanted to know what the thermostat was doing, so I added a 'Power'-device, showing the % applied by the thermostat. This way I can log the % into my influx db.

Will be in my pul request.

**Comment by 999LV** [comment]
I understand the rationale of this, but in my humble view this does not belong to the master branch... am always keen to minimize additional devices and avoid clutter in Domoticz.

**Comment by rrozema** [comment]
Yes, if it was working perfectly, I would agree. But it doesn't for most people in my experience. Having a power indicator let's people see wat the thermostat is doing. Domoticz is not a main stream product, current users are all 'tinkerers' that want to see what's going on. I think most of the current Domoticz users will appreciate more insight in what's going on. This is why they chose to do it themselves and not buy a Nest thermostat.
