### ISSUE TITLE
Go beyond rooms

### ISSUE THREAD

**Issue by flatsiedatsie** [999LV/SmartVirtualThermostat#5]
Currently this plugin is focussed on being a thermostat for houses. But a virtual PID temperature controller can be useful for a lot of things.
- Aquarium temperature
- Meat smoker
- Egg Incubator
- Beer brewing
- Ceramic and porselain art oven
- Reflow oven for electronics
- Pizza oven
- Etc

At the same time there are people who would like the have a very precise cooler instead of a heater.

- Smart Wine chiller / cellar
- Ice Cream maker
- Molecular cooking

So my question is: how could this plugin be made in such a way that it has different profiles?
- Room sized (slow, small changes over time)
- Box sized devices, like ovens (fast changing)

Currently the plugins has minimums like 60 minutes for the forced function, and 5 minutes for the learning function.

(Using the current thermostat should probably already be done with a relay that is somewhat smart itself. I've built such a relay for MySensors and will release that soon. It checks for a connection to Domoticz, has a maximum heater on duration, maximum temperature check, sensor failure, etc.)

**Comment by 999LV** [comment]
I do like the beer brewing and wine cellar applications, but that being said, the plugin is aimed at bringing comfort to homes. I would assume most of the booze or similar applications can accomodate hyterisis thermostats ?

**Comment by sbr2004** [comment]
Unfortunately domotocz with SVT is very unstable, crashes rather often. Thermostat algorithm is very good, but platform is not production grade.

**Comment by 999LV** [comment]
@sbr2004, you might want to try out version 0.4.0 that shuld address a recent cause of instability with Domoticz.
