### ISSUE TITLE
Version 0.4.13 does not work with Domoticz Beta versions

### ISSUE THREAD

**Issue by fjumelle** [999LV/SmartVirtualThermostat#63]
Due to the way the version is coded in Domoticz Beta "YYYY.N (build XXX)", the plugin start fails line 135:
versionminor = int(versionstr.split(".")[1])
ValueError: invalid literal for int() with base 10: '2 (build 15636)' 

BTW, the check line 136 (if versionmajor >= 2023 and versionminor >= 2) will not work for 2024.1 :)

**Comment by feelingwalnut** [comment]
changing line 135 to         versionminor = int(versionstr.split(".")[0])
removes the error. not sure if it is actually working but no errors in log, still learning this stuff.
(don't take advise from someone still trying to figure out where to insert desired room temperature)

**Comment by 999LV** [comment]
Corrected the code in version 0.4.14, [https://github.com/999LV/SmartVirtualThermostat/commit/b539be5dec499d480d345039cea17a2545c6305a](url)
Thanks @fjumelle

**Comment by fjumelle** [comment]
Still NOK as version = float(versionstr.split(".")[0]) will return 2023.0 while I have "2023.2 (build XXX)".
version = float(versionstr.split(" ")[0]) with a space instead of a dot will do the job, for official "2023.2" and for beta "2023.2 (build xxxx)".

**Comment by 999LV** [comment]
You are correct. I pushed the wrong file. Should be a space indeed
