### ISSUE TITLE
Domoticz received fatal signal 11 !

### ISSUE THREAD

**Issue by cyrilpascal** [999LV/SmartVirtualThermostat#7]
Hello
I plan to use your great plugin to manage 6 area in my house.
Each area is attache with a new "smart virtual thermostat" hardware. 
When I create the 4th aera no problem but if I restart domoticz it produce a signal 11
during domoticz startup.
So i decide to remove the plugin and i was able remove the 4th hardware.
I re-install the plugin and was able to create 6 type SVT hardware and domoticz doesn't crash.
But when if I restart domoticz same issue.
So I remove again the 6 and test by creating one by one and restarting domoticz after each creation.
It's how i detect that the problem is systematic from the fourth.

The strange thing is that it's work still domoticz is not restart. So may be something differ when you allocate the new "hardware" when domoticz is running from when domoticz is starting with the existing "hardware". 
Thanks for your help.

Domoticz : V3.8153
SVT plugin : 0.3.8
Python 3.5.2
Linux armbian
Platform : Orange PI Zero 512

2018-03-30 06:07:07.407  Error: Domoticz received fatal signal 11 !...
2018-03-30 06:07:07.408  Error: Domoticz received fatal signal 6 while backtracing !...
2018-03-30 06:07:07.411  Error:   /home/pi/domoticz/domoticz() [0x1cdc48]
2018-03-30 06:07:07.411  Error:   /home/pi/domoticz/domoticz(_Z14signal_handleri+0x58) [0x1cdd00]
2018-03-30 06:07:07.411  Error:   /lib/arm-linux-gnueabihf/libc.so.6(+0x25260) [0xb6b8d260]

**Comment by 999LV** [comment]
That is indeed a very ambitious project... I suspect this is not an issue with the plugin istelf but rather with the python plugin framework and/or the broader domoticz reaching some limits as more plugin instances are added.
I will try to replicate on a test machine with this and other plugins to confirm. In that case we have to ask @dnpwwo - the developer of the plugin framework - for help.

**Comment by dnpwwo** [comment]
No reason why 6 plugins can't run at the same time.

Are you running the lastest beta?  The frame logging has been uplifted so could you run the plugins in debug mode and post the result

**Comment by cyrilpascal** [comment]
Hello
I move from stable (V3.8153) to beta and it works perfectly with the latest beta release 👍 
Arm 32bit (Raspberry/cube/...) | 3.9156 |   | 2018-04-01
Thanks for your help
