### ISSUE TITLE
Accessing parameters

### ISSUE THREAD

**Issue by cyrilpascal** [999LV/SmartVirtualThermostat#8]
Hello
I currently use 6 Virtual thermostat and i  would like to access parameters from each one via lua dzVent: list of devices per type.
Have you any idea. May be it will be possible to store them in user variable.
Thanks for your help

**Comment by 999LV** [comment]
@cyrilpascal  I am not familiar with dzVents and not sure which plugin parameters you want to access...
 The plugin’s switches and setpoints should be accessible from the event system ? I never tried but these are domoticz devices like any others I assume.
But may be I simply do not understand what you are trying to achive...

**Comment by cyrilpascal** [comment]
@999LV Hello i just want to access the list of idx for the heating switch use per zone. To be able to calculate de power consumption per zone. I can manage a global set of tables per zone but i prefer to do things as simple as possible (no duplication of data). The other advantage is in case of failure in the chain (server, domoticz, mqtt, heating controller(tasmota)) I would be able to access directly to the list of heating controller per zone. Other idea for the future, actually each zone is independent.  But when a door is open between two zone may be it will be possible to create a global zone with concatenation of all the parameters etc etc ...
Thanks for your interest i will ask to @dannybloe for the technical detail.

**Comment by cyrilpascal** [comment]
@999LV I Just leave the request for information in the domoticz dzVent forum
May be somebody will answer
https://www.domoticz.com/forum/viewtopic.php?f=59&t=23034#p177528

**Comment by 999LV** [comment]
@cyrilpascal , so you in fact you want to read the hardware parameters for each plugin instance... isn’t this an overkill ? You do not change the list of heaters that often...
