### ISSUE TITLE
Corrupted Switches in Domoticz V4.9700

### ISSUE THREAD

**Issue by AnroyVlug** [999LV/SmartVirtualThermostat#9]
After upgrading to Domoticz v4.9700 Switches are corrupted, reinstalling the plug-in has no effect!

![image](https://user-images.githubusercontent.com/40721442/42127433-d2bc22e0-7c98-11e8-896a-1dda9e80b938.png)

Kind regards, Anroy

**Comment by 999LV** [comment]
Please check about issues like this on the domoticz forum... this issue has nothing to do with the plugin: it is well known that when upgrading domoticz you need to clear the cache and app cache and sometimes even remove some compressed files in the www folder of domoticz

**Comment by AnroyVlug** [comment]
That was the problem, just new to Domoticz Thanks!
